#!/bin/bash

TMPDIR=$(mktemp -d)

function install_yay() {
	pushd $TMPDIR >/dev/null
	git clone https://aur.archlinux.org/yay.git
	pushd yay >/dev/null
	makepkg -si
	popd >/dev/null
	popd >/dev/null
}

sudo pacman -Sy
sudo pacman -S --needed git --noconfirm
command -v yay >/dev/null || install_yay
yay -S --needed rsync git openssh unzip --noconfirm
yay -S --needed neovim dmenu dunst tmux ttf-hack-nerd wezterm-git --noconfirm
yay -S --needed hyprland wofi kitty waybar hyprpaper hyprlock xdg-desktop-portal-hyprland dunst pipewire wireplumber hyprpolkitagent --noconfirm

[ -d home ] && rsync -r home/ $HOME/
[ -d config ] && rsync -r config/ $HOME/.config
[ ! -d $HOME/.config/tmux/plugins/tpm ] && git clone https://github.com/tmux-plugins/tpm $HOME/.config/tmux/plugins/tpm
ln -sf $HOME/.config/tmux/tmux.conf $HOME/.tmux.conf

rm -r $TMPDIR

