#!/usr/bin/env bash
#      _ _____  ____        _
#     | |__  / |  _ \  ___ | |_ ___
#  _  | | / /  | | | |/ _ \| __/ __|
# | |_| |/ /_  | |_| | (_) | |_\__ \
#  \___//____| |____/ \___/ \__|___/
#
# Use at your own risk :)
#
# This will overwrite all the files in config and home that
# are in this git repo. While the config management portion of
# this script can be run on most Posix-compliant systems, the
# bootstrapping (-s flag) is only made for Arch Linux (btw)
# with Hyprland as its window manager.
#
# If you wish to use the dots as-is, make sure you have git, rsync
# and curl installed to your system
#
# Built with <3 (and because I have done this too many times)
# - jzlotek
set -uxe

CWD=$(pwd)

TMPDIR=$(mktemp -d)
DOTS_BRANCH="${DOTS_BRANCH:-master}"
GIT_REPO_RAW_FILE_URL="${GIT_REPO_RAW_FILE_URL:-https://raw.githubusercontent.com/jzlotek/dots/refs/heads/$DOTS_BRANCH}"
DOTS_REPO="${DOTS_REPO:-git@github.com:jzlotek/dots.git}"
CONFIG_DIR="${XDG_CONFIG_DIR:-$HOME/.config}"
INSTALL_DIR="${XDG_DATA_HOME:-$HOME/.local/share}"
SYNC="false"
FULL="false"
DIRECTORY=""

function cleanup() {
	rm -r $TMPDIR
}
function restore_cwd() {
	if [ $(pwd) != $CWD ]; then
		cd $CWD
	fi
}
trap cleanup EXIT INT TERM
trap restore_cwd EXIT INT TERM


print_help() {
	cat <<-EOF
	install dotfiles

	By default will only install TUI app configs

	-s requires sudo. sync packages (Arch only right now btw)
	-f full install. Installes configs used for desktop env
	-h print this message and exit
	EOF
}

function check_pkg_installed() {
	if command -v "$1" >/dev/null; then
		printf "\e[32m%s found\n\e[0m" "$1"
	else
		printf "\e[31m%s NOT found\n\e[0m" "$1"
		exit 1
	fi
}

function install_yay() {
	command -v yay >/dev/null && return
	check_pkg_installed git
	pushd "${TMPDIR}" >/dev/null
	git clone https://aur.archlinux.org/yay.git
	pushd yay >/dev/null
	makepkg -si
	popd >/dev/null
	popd >/dev/null
}

function setup_chaotic_aur() {
	sudo pacman-key --recv-key 3056513887B78AEB --keyserver keyserver.ubuntu.com
	sudo pacman-key --lsign-key 3056513887B78AEB
	sudo pacman -U 'https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-keyring.pkg.tar.zst' --noconfirm
	sudo pacman -U 'https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-mirrorlist.pkg.tar.zst' --noconfirm

	if ! grep -q "/etc/pacman.d/chaotic-mirrorlist" "/etc/pacman.conf"; then
		sudo bash -c 'cat >> /etc/pacman.conf <<-EOF
[chaotic-aur]
Include = /etc/pacman.d/chaotic-mirrorlist
EOF
'
	fi

}

function install_ohmyzsh() {
	export ZSH="${CONFIG_DIR}/oh-my-zsh"
	if [ ! -d "${ZSH}" ]; then
		sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
	fi
}

function install_tmux() {
	[ ! -d "${CONFIG_DIR}/tpm/plugins/tpm" ] && git clone https://github.com/tmux-plugins/tpm "${CONFIG_DIR}/tpm/plugins/tpm"
	ln -sf "${CONFIG_DIR}/tmux/tmux.conf" $HOME/.tmux.conf
}

function sync_packages() {
	sudo pacman -Sy
	sudo pacman -S --needed git curl --noconfirm
	install_yay

	packages_file=packages.csv
	if [ ! -f "${packages_file}" ]; then
		packages_file=$(mktemp /tmp/packages.csv.XXX)
		curl -o "${packages_file}" -L0 "${GIT_REPO_RAW_FILE_URL}/packages.csv"
	fi
	yay -S --needed --noconfirm >/dev/null $(sed '/^\s*#/d' "${packages_file}" | tr "\n" " " < "${packages_file}")
	rm -f "${packages_file}"
}

function install_dotfiles() {
	if [ "${FULL}" = "true" ]; then
		stow wm -t "${HOME}" --dotfiles
		# dot_local/bin/setbg wm/dot-config/hypr/wallpaper.png
	fi
	set -eu

	if ! chezmoi="$(command -v chezmoi)"; then
		bin_dir="${HOME}/.local/bin"
		chezmoi="${bin_dir}/chezmoi"
		echo "Installing chezmoi to '${chezmoi}'" >&2
		if command -v curl >/dev/null; then
			chezmoi_install_script="$(curl -fsSL get.chezmoi.io)"
		elif command -v wget >/dev/null; then
			chezmoi_install_script="$(wget -qO- get.chezmoi.io)"
		else
			echo "To install chezmoi, you must have curl or wget installed." >&2
			exit 1
		fi
		sh -c "${chezmoi_install_script}" -- -b "${bin_dir}"
		unset chezmoi_install_script bin_dir
	fi

	# POSIX way to get script's dir: https://stackoverflow.com/a/29834779/12156188
	script_dir="$(cd -P -- "$(dirname -- "$(command -v -- "$0")")" && pwd -P)"

	set -- init --apply --source="${script_dir}"

	echo "Running 'chezmoi $*'" >&2
	"$chezmoi" init https://github.com/jzlotek/dots.git
	if [ $DOTS_BRANCH != master ]; then
		cd $("$chezmoi" source-path)
		git checkout $DOTS_BRANCH
	fi
	"$chezmoi" apply --force
}

while getopts d:shf opt; do
	case $opt in
		s)
			SYNC="true"
			;;
		f)
			FULL="true"
			;;
		d)
			DIRECTORY=$(readlink -f "${OPTARG}")
			;;
		h)
			print_help
			exit 0
			;;
		*)
			exit 1
			;;
	esac
done

[ $SYNC = "true" ] && setup_chaotic_aur && sync_packages

check_pkg_installed git
check_pkg_installed curl
check_pkg_installed stow

install_ohmyzsh
install_tmux

install_dotfiles

echo "Success"
